name: Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: version tag
        required: false

jobs:
  package-linux:
    # needs: create-destroy-tests
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python dependencies
        run: |
          pip install pipenv
          pipenv install --deploy
          source $(pipenv --venv)/bin/activate
      - name: Package
        run: |
          if [ -z "$VERSION" ]; then export VERSION=$(echo "$GITHUB_REF" | sed 's|refs/tags/v||'); fi
          make build-binary
          cd dist/opta
          zip -r opta.zip ./*
      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/opta/opta.zip
          asset_name: opta_linux.zip
          asset_content_type: application/zip
